# ARCHITECTURE
decoder_model_dimension: 256
encoder_model_dimension: 512
decoder_num_heads: [4, 4, 4, 4]  # the length of this defines the number of layers
encoder_num_heads: [4, 4, 4, 4]  # the length of this defines the number of layers
encoder_feed_forward_dimension: 1024
decoder_feed_forward_dimension: 1024
decoder_prenet_dimension: 256
encoder_prenet_dimension: 512
encoder_attention_conv_filters: 512
decoder_attention_conv_filters: 512
encoder_attention_conv_kernel: 3
decoder_attention_conv_kernel: 3
encoder_max_position_encoding: 1000
decoder_max_position_encoding: 10000
postnet_conv_filters: 256
postnet_conv_layers: 5
postnet_kernel_size: 5
encoder_dense_blocks: 1
decoder_dense_blocks: 0

# TRAINING
dropout_rate: 0.1
decoder_prenet_dropout_schedule:  # dropout scheduling for the decoder status
  - [0, 0.]
learning_rate_schedule:
  - [0, 1.0e-4]
head_drop_schedule:  # head-level dropout: how many heads to set to zero at training time
  - [0, 0]
max_steps: 800_000
bucket_boundaries: [200, 300, 400, 500, 600, 700, 800, 900, 1000, 1200] # mel bucketing
bucket_batch_sizes: [64, 42, 32, 25, 21, 18, 16, 14, 12, 6, 1]
debug: False

# LOGGING
validation_frequency: 1_000
prediction_frequency: 1_000
weights_save_frequency: 5_000
train_images_plotting_frequency: 1_000
keep_n_weights: 5
keep_checkpoint_every_n_hours: 12
n_steps_avg_losses: [100, 500, 1_000, 5_000]  # command line display of average loss values for the last n steps
n_predictions: 5
prediction_start_step: 1_000
audio_start_step: 5_000
audio_prediction_frequency: 5_000 # converting to glim takes time
